### ISSUE TITLE
私有Cocoapods安装不了

### ISSUE THREAD

**Issue by SenorSamuel** [PlatONnetwork/ATON-iOS#2]
[!] Unable to add a source with url `git@192.168.9.66:weixuening/JuzixSpecs.git` named `9-juzixspecs`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

**Comment by danielgogo** [comment]
Fixed in version v0.4.0

https://github.com/PlatONnetwork/ATON-iOS/commit/c88c68f5cded61a06a0721a6dde8304aeff189bb
